#!/bin/bash

DEST_REPO=$1
if [ "$DEST_REPO" == '' ]; then
    echo "Usage: create_symlinks <git repository path>"
    exit 1
fi

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

if [[ $DEST_REPO == */ ]]; then
    DEST_REPO_HOOKS=$DEST_REPO.git/hooks
else
    DEST_REPO_HOOKS=$DEST_REPO/.git/hooks
fi

if [ "$(which diffiles)" == '' ]; then
    echo 'diffiles not found in PATH, creating symlink to /usr/bin'
    sudo ln -s ${DIR}/diffiles /usr/local/bin/diffiles
fi

if [ "$(which checkpep8)" == '' ]; then
    echo 'checkpep8 not found in PATH, creating symlink to /usr/bin'
    sudo ln -s ${DIR}/checkpep8 /usr/local/bin/checkpep8
fi

if ! [ -x "$(command -v pycodestyle)" ]; then
    if ! [ -x "$(command -v pep8)" ]; then
        echo "WARNING: please install pycodestyle or pep8 (pip install pycodestyle)"
    fi
fi

if ! [ -x "$(command -v pyflakes)" ]; then
    echo "WARNING: please install pyflakes (pip install pyflakes)"
fi

echo "creating symlinks in $DEST_REPO_HOOKS"

make_link() {
    if [ -f ${DEST_REPO_HOOKS}/$1 ]; then
        mv ${DEST_REPO_HOOKS}/$1 ${DEST_REPO_HOOKS}/$1.old
    fi
    ln -s ${DIR}/$1 ${DEST_REPO_HOOKS}/$1
}

make_link post-checkout
make_link post-update
make_link post-merge
make_link post-commit
make_link prepare-commit-msg
