#!/bin/sh

DEST_REPO=$1
if [ "$DEST_REPO" == '' ]; then
    echo "Usage: create_symlinks <git repository path>"
    exit 1
fi

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

if [[ $DEST_REPO == */ ]]; then
    DEST_REPO_HOOKS=$DEST_REPO.git/hooks
else
    DEST_REPO_HOOKS=$DEST_REPO/.git/hooks 
fi

if [ "$(which diffiles)" == '' ]; then
    echo 'diffiles not found in PATH, creating symlink to /usr/bin'
    sudo ln -s ${DIR}/diffiles /usr/bin/diffiles 
fi

if [ "$(which checkpep8)" == '' ]; then
    echo 'checkpep8 not found in PATH, creating symlink to /usr/bin'
    sudo ln -s ${DIR}/checkpep8 /usr/bin/checkpep8 
fi

echo "creating symlinks in $DEST_REPO_HOOKS"
if [ -f ${DEST_REPO_HOOKS}/post-checkout ]; then
    mv ${DEST_REPO_HOOKS}/post-checkout ${DEST_REPO_HOOKS}/post-checkout.old 
fi
ln -s ${DIR}/post-checkout ${DEST_REPO_HOOKS}/post-checkout

if [ -f ${DEST_REPO_HOOKS}/post-update ]; then
    mv ${DEST_REPO_HOOKS}/post-update ${DEST_REPO_HOOKS}/post-update.old 
fi
ln -s ${DIR}/post-update ${DEST_REPO_HOOKS}/post-update

if [ -f ${DEST_REPO_HOOKS}/post-merge ]; then
    mv ${DEST_REPO_HOOKS}/post-merge ${DEST_REPO_HOOKS}/post-merge.old 
fi
ln -s ${DIR}/post-merge $DEST_REPO_HOOKS/post-merge

if [ -f ${DEST_REPO_HOOKS}/post-commit ]; then
    mv ${DEST_REPO_HOOKS}/post-commit ${DEST_REPO_HOOKS}/post-commit.old 
fi
ln -s ${DIR}/post-commit $DEST_REPO_HOOKS/post-commit
