#!/bin/sh

CURR_BRANCH=`git rev-parse --abbrev-ref HEAD`

git checkout master 2> /dev/null > /dev/null
git pull 2> /dev/null > /dev/null
git checkout $CURR_BRANCH 2> /dev/null > /dev/null
git diff --name-only master

